services:

  rabbitmq:
    image: "rabbitmq:4.0.2-management"
    container_name: rabbitmq
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  generator:
    build: ./generator
    container_name: generator
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      USERNAME: admin
      PASSWORD: admin
      QUEUE_NAME: queue_sensors
    command: python main.py
    
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    restart: always
    volumes: 
      - type: tmpfs
        target: /data/db

  onboard-system:
    build: ./OnboardSystem
    container_name: onboard-system
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      ASPNETCORE_URLS: http://+:5109
      OnboardDatabase__ConnectionString: mongodb://mongodb:27017
      OnboardDatabase__DatabaseName: Onboard
      OnboardDatabase__SensorsCollectionName: Sensors
      rabbitmq__host: rabbitmq
      rabbitmq__username: admin
      rabbitmq__password: admin
      rabbitmq__queueName: queue_sensors
      BLOCKCHAIN_ENDPOINT: ${BLOCKCHAIN_ENDPOINT}
      CONTRACT_ADRESS: ${CONTRACT_ADRESS}
      MAIN_WALLET_PRIVATE_KEY: ${MAIN_WALLET_PRIVATE_KEY}
      NUMBER_OF_SENSORS: ${NUMBER_OF_SENSORS}
      SENSOR_1_PUBLIC_KEY: ${SENSOR_1_PUBLIC_KEY}
      SENSOR_2_PUBLIC_KEY: ${SENSOR_2_PUBLIC_KEY}
      SENSOR_3_PUBLIC_KEY: ${SENSOR_3_PUBLIC_KEY}
      SENSOR_4_PUBLIC_KEY: ${SENSOR_4_PUBLIC_KEY}
      SENSOR_5_PUBLIC_KEY: ${SENSOR_5_PUBLIC_KEY}
      SENSOR_6_PUBLIC_KEY: ${SENSOR_6_PUBLIC_KEY}
      SENSOR_7_PUBLIC_KEY: ${SENSOR_7_PUBLIC_KEY}
      SENSOR_8_PUBLIC_KEY: ${SENSOR_8_PUBLIC_KEY}
      SENSOR_9_PUBLIC_KEY: ${SENSOR_9_PUBLIC_KEY}
      SENSOR_10_PUBLIC_KEY: ${SENSOR_10_PUBLIC_KEY}
      SENSOR_11_PUBLIC_KEY: ${SENSOR_11_PUBLIC_KEY}
      SENSOR_12_PUBLIC_KEY: ${SENSOR_12_PUBLIC_KEY}
      SENSOR_13_PUBLIC_KEY: ${SENSOR_13_PUBLIC_KEY}
      SENSOR_14_PUBLIC_KEY: ${SENSOR_14_PUBLIC_KEY}
      SENSOR_15_PUBLIC_KEY: ${SENSOR_15_PUBLIC_KEY}
      SENSOR_16_PUBLIC_KEY: ${SENSOR_16_PUBLIC_KEY}
    ports:
      - "5109:5109"
    restart: always

  frontend:
    build: ./on-board-frontend
    ports:
      - "8080:80"
    container_name: on-board-frontend
